### ISSUE TITLE
Add debug box with metrics, last update, api quota, etc

### ISSUE THREAD

**Issue by moul** [moul/depviz#214]
┆Issue is synchronized with this [Trello card](https://trello.com/c/9eMhyhyM)

**Comment by moul** [comment]
@appigram I plan to create a call that will give you some metrics from the server side, but you can already setup something to see the info available from the client side (FPS, amount of nodes, amount of edges, etc)

**Comment by appigram** [comment]
@moul a few metrics (FPS, amount of nodes, amount of edges) integrated to the version for development. Let me know if any metrics needed
