### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by moul** [moul/depviz#217]
Interesting stuff:

* Dat.gui (https://github.com/dataarts/dat.gui, http://workshop.chromeexperiments.com/examples/gui/)
* Tabler (https://github.com/tabler/tabler, https://tabler.io)
* Bootstrap Studio (https://bootstrapstudio.io/)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Bfs6iWsi)

**Comment by moul** [comment]
@appigram can you setup this soon, so we can use it as soon as we have things that we are unsure about, i.e., "default duration for gantt" etc?

**Comment by appigram** [comment]
@moul yep, I can setup one of this gui, Tabler is looks good

**Comment by moul** [comment]
:+1:

I also love Dat.gui that can be added as additional way of having more and more flags

Can you try to mix one nice gui (tabler) + dat.gui for all the things that can be customized?

I think that we will need some time to clearly define the "simple menu", for now we need an exhaustive menu

**Comment by appigram** [comment]
A basic version of TablerUI added. Dat.gui looks interesting, but I don't where I can use it for now. I think we can use Dat.gui later without any issues
