### ISSUE TITLE
Improved infobox

### ISSUE THREAD

**Issue by moul** [moul/depviz#288]
Hey, looks very nice, can you, add those pieces of info:

* keep the last clicked box "highlighted" or with a visual border, something that explicitly help remembering which box was just clicked
* author name + link to its profile
* state: "open", "closed" with different color if open or closed to make things easy to visualize
* the kind (Issue, Pull Request), there is an icon available somewhere in the repo, maybe directly in the card template
* the driver (GitHub)
* the infobox title should be "local_id", not "id"
![manfreds-imac - Screen Shot 2020-04-14 at 10 24 12](https://user-images.githubusercontent.com/94029/79202564-17293180-7e3a-11ea-8e4c-748ed980a94c.png)

![manfreds-imac - Screen Shot 2020-04-14 at 10 29 04](https://user-images.githubusercontent.com/94029/79203056-c49c4500-7e3a-11ea-857b-c895ab31c375.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/JyRFNWLJ)

**Comment by appigram** [comment]
Hi @moul , there are changes for InfoBox and some hints:
States inside info box: "open" - green color on the top, "closed, missing - grey color
About "keep the last clicked box "highlighted" or with a visual border, something that explicitly help remembering which box was just clicked" - this feature added in last PR https://github.com/moul/depviz/pull/287 , but seems sometimes misclick on card occurs [http://joxi.ru/eAO5ljyt9o8gkm](http://joxi.ru/eAO5ljyt9o8gkm), I try to dive into graph rendering to fix
