### ISSUE TITLE
depviz handle . comment

### ISSUE THREAD

**Issue by Doozers** [moul/depviz#662]
```
id:"https://github.com/gnolang/gno/issues/539" created_at:<seconds:1677257369 > updated_at:<seconds:1678276791 > local_id:"gnolang/gno#539" kind:Issue title:"Improve UX with better typography?" description:"The official Gno.land UX is built around Markdown.\r\n\r\nThis issue is to get feedback and discuss how we could improve the overall UX with better typography.\r\n\r\nRelated with #439.\r\nPart of #540.\r\n\r\nCan be used for testing: https://staging.gno.land/r/demo/markdown_test." driver:GitHub state:Open num_comments:4 estimated_duration:"undefined" has_author:"https://github.com/moul" has_owner:"https://github.com/gnolang/gno" has_label:"https://github.com/gnolang/gno/labels/good first issue" has_label:"https://github.com/gnolang/gno/labels/help wanted" is_related_with:"https://github.com/gnolang/gno/issues/439." is_part_of:"https://github.com/gnolang/gno/issues/540." has_part:"https://github.com/gnolang/gno/issues/540."
```

As you can see in this printed `task` some `relation` are marked with a `.` at the end of it, this totally break the current Depviz implementation. This is due to either a bad usage of Depviz or a program's unexpected behavior.

![image](https://user-images.githubusercontent.com/71719097/232067538-135c667d-f602-4934-ae8c-2e961abe30b4.png)

This is a example of a problematic usage (the one of the task printed bellow), we need to chose:
- Depviz should handle this, modify multipmuri parse regex to handle it in a more general way.
- Depviz comments must respect a defined format: `[keyword associated-issue\n]` or even `[keyword associated-issue.]`

@moul wdyt ?

┆Issue is synchronized with this [Trello card](https://trello.com/c/uATsQ6z3)

**Comment by moul** [comment]
I think we need to extend `multipmuri` for this case and additional ones in the future.

I'm for setting format constraints for uncommon things like `depviz:key=value`, but this specific case is understood by other tools, and Depviz should too.

By the way, I think it makes sense to merge `multipmuri` as a subpackage of depviz. Feel free to do it, then I can archive `multipmuri` with a link to the new package.
